[uwsgi]

# 注意：此端口 (8092) 与 CherryPy 默认端口 (8081) 不同
# python main.py → http://localhost:8081
# uwsgi --ini uwsgi.ini → http://localhost:8092
http = 0.0.0.0:8092

# 项目目录
chdir = /root/SUSTechPOINTS

# 指定项目的 Application
module = main:application

master = true

buffer-size = 65536

# 进程数
processes = 4

# 每进程线程数
threads = 2
